# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
import numpy as np

## Creating arrays


In [2]:
arr0 = np.zeros(5)
arr0

array([0., 0., 0., 0., 0.])

In [3]:
arr1 = np.ones(3)
arr1

array([1., 1., 1.])

In [35]:
arrfull = np.full(10, 400)
arrfull

array([400, 400, 400, 400, 400, 400, 400, 400, 400, 400])

In [36]:
myarr = np.array([2, 3, 4, 5])

myarr

array([2, 3, 4, 5])

In [38]:
myarr[3]

np.int64(5)

In [39]:
myarr[3] = 432

In [40]:
myarr

array([  2,   3,   4, 432])

In [42]:
rg = np.arange(3, 11, 2)
rg

array([3, 5, 7, 9])

In [43]:
nspace = np.linspace(0, 100, 11)
nspace

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays


In [2]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.full((2, 4), 99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

In [15]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)

In [16]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr1[1:3, 1:3] = ([20, 30],
                   [40, 50])

In [20]:
arr1

array([[ 1,  2,  3],
       [ 4, 20, 30],
       [ 7, 40, 50]])

In [ ]:
arr1[1, :]  

array([ 4, 20, 30])

In [25]:
arr1[1:, 1:3]  

array([[20, 30],
       [40, 50]])

## Randomly generated arrays


In [32]:
np.random.seed(3)
np.random.rand(3, 4)

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761],
       [0.89294695, 0.89629309, 0.12558531, 0.20724288],
       [0.0514672 , 0.44080984, 0.02987621, 0.45683322]])

In [36]:
np.random.randint(low=10, high=15, size=(3, 4))

array([[12, 14, 10, 10],
       [11, 11, 11, 12],
       [13, 14, 14, 13]], dtype=int32)

In [37]:
np.random.randn(3, 4)

array([[ 0.58407687, -1.12779274,  0.83999837,  0.36827404],
       [-0.47327954,  1.170188  ,  0.06006215, -0.09791443],
       [-0.51751243,  1.8427204 ,  0.2630727 , -2.25009722]])

## Element-wise operations


In [49]:
arr1

array([[ 1,  2,  3],
       [ 4, 20, 30],
       [ 7, 40, 50]])

In [51]:
100 * arr1 -25

array([[  75,  175,  275],
       [ 375, 1975, 2975],
       [ 675, 3975, 4975]])

In [52]:
arr1 / 2

array([[ 0.5,  1. ,  1.5],
       [ 2. , 10. , 15. ],
       [ 3.5, 20. , 25. ]])

In [63]:
arr2 = arr1 * 2

In [64]:
arr2

array([[  2,   4,  12],
       [  8,  40, 120],
       [ 14,  80, 200]])

## Comparison operations

In [56]:
arr1 > arr2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [58]:
arr2 > arr1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [59]:
arr1[:, 2] = arr1[:, 2]  * 2

In [69]:
arr1

array([[  1,   2,   6],
       [  4,  20,  60],
       [  7,  40, 100]])

In [68]:
arr2

array([[  2,   4,  12],
       [  8,  40, 120],
       [ 14,  80, 200]])

In [70]:
arr1[arr1 < arr2]

array([  1,   2,   6,   4,  20,  60,   7,  40, 100])

In [71]:
arr2[arr2 > arr1]

array([  2,   4,  12,   8,  40, 120,  14,  80, 200])

## Summarizing operations

In [72]:
arr1.sum()

np.int64(240)

In [73]:
arr2.sum()

np.int64(480)

In [74]:
arr2.min()

np.int64(2)

In [75]:
arr2.max()

np.int64(200)

In [77]:
round(arr2.std(), 2)

np.float64(64.31)

In [78]:
arr2.mean()

np.float64(53.333333333333336)

### Next

Linear algebra refresher