# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
import numpy as np

## Creating arrays


In [32]:
arr0 = np.zeros(5)
arr0

array([0., 0., 0., 0., 0.])

In [33]:
arr1 = np.ones(3)
arr1

array([1., 1., 1.])

In [35]:
arrfull = np.full(10, 400)
arrfull

array([400, 400, 400, 400, 400, 400, 400, 400, 400, 400])

In [36]:
myarr = np.array([2, 3, 4, 5])

myarr

array([2, 3, 4, 5])

In [38]:
myarr[3]

np.int64(5)

In [39]:
myarr[3] = 432

In [40]:
myarr

array([  2,   3,   4, 432])

In [42]:
rg = np.arange(3, 11, 2)
rg

array([3, 5, 7, 9])

In [43]:
nspace = np.linspace(0, 100, 11)
nspace

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays


In [2]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.full((2, 4), 99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

In [13]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr1[1:3, 1:3] = ([20, 30],
                   [40, 50])

In [12]:
arr1

array([[ 1,  2,  3],
       [ 4, 20, 30],
       [ 7, 40, 50]])

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays


array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

## Element-wise operations


array([0, 1, 2, 3, 4])

array([1.  , 1.44, 1.96, 2.56, 3.24])

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison operations

array([0, 1, 2, 3, 4])

array([False, False,  True,  True,  True])

array([1.  , 1.44, 1.96, 2.56, 3.24])

array([False, False,  True,  True,  True])

array([2, 3, 4])

## Summarizing operations

array([0, 1, 2, 3, 4])

np.float64(1.4142135623730951)

np.int64(0)

### Next

Linear algebra refresher